XMLParser: ./* ../* ../../CityModel/*
	g++ ./*.cpp \
		../Module.cpp \
		../../CityModel/*.cpp \
		../../CityModel/ADE/*.cpp \
		../../CityModel/ADE/document/*.cpp \
		../../CityModel/ADE/temporal/*.cpp \
	-o XMLParser \
		-I ../ \
		-I ./ \
		-I ../../CityModel \
		-lxml2 -I/usr/include/libxml2 \
		-lGL -lGLU -lGLEW
